### ISSUE TITLE
[regression] add flag form first step shouldn't have the machine name and link type

### ISSUE THREAD

**Issue by joachim-n** [socketwench/flag-drupal8#115]
This was changed from Flag 7.x-2.x to Flag 7.x-3.x. The first page should just be selecting the flag type.

**Comment by socketwench** [comment]
This behavior was changed because the entity type also needs to be selected prior to building the Flag Add Form. Without this, the add form would have a great deal more complexity as we would have to select the Flag Type Plugin then rebuild the form. 

For this reason, UI was patterned after the View Add UI instead, which includes the label and machine name. Going forward, this would be more natural for site builders than a direct port of the 7.x-3.x UI.

**Comment by joachim-n** [comment]
> This behavior was changed because the entity type also needs to be selected prior to building the Flag Add Form.

That's the bit I mean.

> For this reason, UI was patterned after the View Add UI instead, which includes the label and machine name. Going forward, this would be more natural for site builders than a direct port of the 7.x-3.x UI.

I don't think we should be doing that. The Views UI starts off with a view wizard interface to save site builders from the huge complexity of building a view. The idea is that in simple cases they can get most things done in the wizard and in complex cases you still save quite a few clicks in the main UI.

But Views has a slow UI: everything you change requires a new modal form to be AJAXed in.

Flag doesn't have this at all. There's no need to split the form into two parts like this.

(In fact, we don't even need the first part to be a form -- it can be a list of links like the /node/add page, which will simplify our code considerably. Having to submit the first part of the form, and then redirect to the second part is just faffy. But that's another issue.)

**Comment by socketwench** [comment]
It's not just selecting the entity type, though. The add/edit form relies on the flag type plugin for a large amount of settings. The entire purpose of the add page is to build that plugin first so we can build the remainder of the form. The same is also true for the link type plugin. It seemed simpler to compartmentalize the initialization into FlagAddPageForm. 

Originally, the permissions were also set in FlagAddPageForm until we decided to use the core permission page alone. 

Changing this now would require rewriting a lot of FlagAddPageForm, FlagAddForm, FlagEditForm, and FlagFormBase. It seems like a lot of work for something that doesn't seem broken in my view.

**Comment by joachim-n** [comment]
>The add/edit form relies on the flag type plugin for a large amount of settings

Yes, I know that and I agree. Selecting the entity type and thus the flag type plugin upfront is not in question here -- I feel we're talking cross purposes!

> The same is also true for the link type plugin

Changing the link type plugin can be done on the main form, and the different settings AJAX in.

> Changing this now would require rewriting a lot of FlagAddPageForm, FlagAddForm, FlagEditForm, and FlagFormBase. It seems like a lot of work for something that doesn't seem broken in my view.

It's a regression from 7.x-3.x. I did say that starting work on 8.x when you did was premature!

**Comment by Berdir** [comment]
Building a form where you have to select a plugin first and then it loads everything else after with ajax isn't that hard, we're doing just that now with http://cgit.drupalcode.org/monitoring/tree/src/Form/SensorForm.php?h=8.x-1.x, You just have to put everything in a common container and then add ajax stuff to the select, + a non-js fallback button that does more or less the same, mostly for tests.

**Comment by joachim-n** [comment]
> Building a form where you have to select a plugin first and then it loads everything else after with ajax isn't that hard

Cool -- thanks for the tip! We can definitely bear that in mind when we come to that.

**Comment by socketwench** [comment]
The UI change actually does remove some code, but I'm not sure I entirely like the result. Unlike 7.x, there's a lot of entities in 8.x one can flag. Also it does affect how the tests are written (they are currently broken in the PR). 

Given https://github.com/socketwench/flag-drupal8/issues/118, I'd rather keep the old UI and instead and add a "Save and Continue" button to FlagAddPageForm.

**Comment by joachim-n** [comment]
I don't understand how 118 is related.

> Unlike 7.x, there's a lot of entities in 8.x one can flag

Do you mean that the page gets very long when the flag type element is radios?

There is the matter of whether we should make config entities flaggable. On the one hand, there's no reason why not (and IIRC vocabs are flaggable on D7), but there's a bit of a disconnect in that the flaggings are content. So a user might expect the fact their vocab is flagged to make it into the updated configuration, and it won't. That's something to discuss later.

**Comment by socketwench** [comment]
>I don't understand how 118 is related.

Mostly, I was thinking that 118 eliminates the only required entry on the add/edit form when creating the flag. That way, you can make the buttons on the FlagAddPageForm "Create Flag", "Save and Continue", and "Cancel", eliminating a step when creating a flag. 

>There is the matter of whether we should make config entities flaggable. 

Yeah... I was originally going to only allow flagging of content entities, but there doesn't seem to be an easy to only get content entities and not all entities.

**Comment by joachim-n** [comment]
> That way, you can make the buttons on the FlagAddPageForm "Create Flag", "Save and Continue", and "Cancel", eliminating a step when creating a flag. 

That's an interesting idea, but my impression of people's uses of Flag is that they tend to want to customize the texts. Hence it's not like Views where you can hope to cover a lot of cases with the first step.

> but there doesn't seem to be an easy to only get content entities and not all entities.

I'm getting off-topic here, but surely it's possible to distinguish between content and config entities -- it's a pretty fundamental difference! Also, on reflection, I don't see how we can make config entities flaggable, since they don't have a numeric ID. We'd need the proposal made elsewhere to use entityref fields.

**Comment by socketwench** [comment]
> That's an interesting idea, but my impression of people's uses of Flag is that they tend to want to customize the texts. 

Also true.

> ...I don't see how we can make config entities flaggable, since they don't have a numeric ID.

The flaggings store that as a string, not a number, so it should work. That doesn't mean that it shouldn't be an entity ref though. I actually don't remember why we went with strings at the time...probably just because core wasn't ready.

**Comment by socketwench** [comment]
Moved to Drupal.org: https://www.drupal.org/node/2410005
