### ISSUE TITLE
@file docblock must fully qualify class

### ISSUE THREAD

**Issue by joachim-n** [socketwench/flag-drupal8#116]
See https://www.drupal.org/coding-standards/docs#file

**Comment by socketwench** [comment]
Fixed in https://github.com/socketwench/flag-drupal8/commit/696dd0ac9ffb72e5064c8728f92bf00ba7a9ccaf

Let me know if I missed any.

**Comment by joachim-n** [comment]
A search for '* Contains' seems to show you've got them all :)
