### ISSUE TITLE
Flag normal link redirect is broken when Drupal is in a subfolder

### ISSUE THREAD

**Issue by joachim-n** [socketwench/flag-drupal8#119]
My site lives at http://localhost:8888/8-drupal/

When I flag a node, I get sent to http://localhost:8888/8-drupal/8-drupal/node/1 which is a 404.

**Comment by socketwench** [comment]
That might explain the Travis CI failures now that I think about it...

**Comment by socketwench** [comment]
Is the node flagged despite the 404?

**Comment by joachim-n** [comment]
Yes. This is purely because the ?destination string is incorrect, hence the form redirect.

**Comment by Berdir** [comment]
Can you try this with the patch from https://www.drupal.org/node/2350837, that add url string (including leading /) support to destination...

**Comment by joachim-n** [comment]
That doesn't fix it. The URL on the flag link is still:

http://localhost:8888/8-drupal/flag/details/flag/favourites/1?destination=8-drupal/node/1

**Comment by socketwench** [comment]
Yeah, it wouldn't. The problem is that ActionLinkTypeBase::getDestination() is using Url::fromRoute('<current>'), and THAT isn't accounting for the subfolder.

**Comment by Berdir** [comment]
Yes, but why is the destination not "destination=/8-drupal/node/1"? That's what you should get when you have a Url object, and that's what I think should work now.

**Comment by socketwench** [comment]
Moved to Drupal.org: https://www.drupal.org/node/2409883
